import { DocumentsTable } from "./DocumentsTable";
import { Navbar } from "./Navbar";
import Head from "next/head";
import { ReactNode } from "react";

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <div className="bg-slate-100 h-screen">
      <Head>
        <title>Document Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-6">
        <Navbar />
      </div>
      <div className="px-6">{children}</div>
    </div>
  );
};
