import type { NextPage } from "next";
import Head from "next/head";
import { DocumentsTable } from "../components/DocumentsTable";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div className="bg-slate-100 h-screen">
      <Head>
        <title>Document Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-6">
        <Navbar />
      </div>
      <div className="px-6">
        <DocumentsTable />
      </div>
    </div>
  );
};

export default Home;
